import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Landing page
    'landing.title': 'Dollar App',
    'landing.subtitle': 'Pay $1, play for prizes, redeem at restaurants.',
    'landing.getStarted': 'GET STARTED',
    'landing.playFreeNow': 'PLAY FREE NOW',
    'landing.forRestaurants': 'For Restaurants',
    'landing.tryOurGames': 'Try Our Games',
    'landing.howItWorks': 'How It Works',
    'landing.howItWorksSubtitle': 'Join the food game revolution with our simple three-step process',
    'landing.step1.title': '1. Deposit & Play',
    'landing.step1.description': 'Add funds instantly. Enter games for just $1 each.',
    'landing.step2.title': '2. Win Prizes',
    'landing.step2.description': 'Compete for amazing food prizes.',
    'landing.step3.title': '3. Redeem & Enjoy',
    'landing.step3.description': 'Use QR codes at restaurants. Instant verification.',
    'landing.cta.title': 'Ready to Join the Game?',
    'landing.cta.subtitle': 'Start playing today and discover amazing food experiences in your area.',
    'landing.cta.button': 'Create Account',
    'landing.chooseYourGame': 'Choose Your Game',
    'landing.tacoFlyer': 'Taco Flyer',
    'landing.tacoFlyerDesc': 'Guide the taco through obstacles!',
    'landing.currentlyPlaying': 'Currently Playing',
    'landing.hamburgerRunner': 'Hamburger Runner',
    'landing.hamburgerRunnerDesc': 'Run and jump through obstacles!',
    'landing.playNow': 'Play Now',
    'landing.foodBlaster': 'Food Blaster',
    'landing.foodBlasterDesc': 'Shoot the food invaders!',
    'landing.comingSoon': 'Coming Soon',
    'landing.pizzaHunter': 'Pizza Hunter',
    'landing.pizzaHunterDesc': 'Hunt for the perfect slice!',
    // Common UI
    'common.loading': 'Loading...',
    'common.back': 'Back',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.submit': 'Submit',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.home': 'Home',
    'common.dashboard': 'Dashboard',
    'common.logout': 'Logout',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.username': 'Username',
    'common.balance': 'Balance',
    'common.score': 'Score',
    'common.points': 'Points',
    'common.prize': 'Prize',
    'common.winner': 'Winner',
    'common.players': 'Players',
    'common.games': 'Games',
    'common.status': 'Status',
    'common.active': 'Active',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.failed': 'Failed',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Info',
    // Auth pages
    'auth.welcomeBack': 'Welcome back',
    'auth.signInToAccount': 'Sign in to your Dollar App account',
    'auth.continueWithGoogle': 'Continue with Google',
    'auth.orContinueWithEmail': 'Or continue with email',
    'auth.emailAddress': 'Email Address',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.signIn': 'Sign In',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.signUp': 'Sign up',
    'auth.backToMainSite': '← Back to main site',
    'auth.createAccount': 'Create Account',
    'auth.joinCommunity': 'Join the Dollar App community',
    'auth.orCreateWithEmail': 'Or create account with email',
    'auth.chooseUsername': 'Choose a username',
    'auth.createPassword': 'Create a password',
    'auth.confirmPassword': 'Confirm your password',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.oauthNote': 'OAuth accounts are created instantly. Email accounts require verification.',
    // Restaurant auth
    'restaurant.portal': 'Restaurant Portal',
    'restaurant.signInToManage': 'Sign in to manage your games and QR redemptions',
    'restaurant.viewDemo': 'View Demo',
    'restaurant.email': 'Restaurant Email',
    'restaurant.enterRestaurantEmail': 'Enter your restaurant email',
    'restaurant.signInToPortal': 'Sign In to Restaurant Portal',
    'restaurant.dontHaveAccount': "Don't have a restaurant account?",
    'restaurant.registerHere': 'Register here',
    'restaurant.joinAsRestaurant': 'Join as Restaurant',
    'restaurant.createGamesAcceptQR': 'Create games and accept QR redemptions',
    'restaurant.name': 'Restaurant Name',
    'restaurant.enterName': 'Enter your restaurant name',
    'restaurant.createAccount': 'Create Restaurant Account',
    'restaurant.alreadyHaveAccount': 'Already have a restaurant account?',
    'restaurant.features': 'Restaurant Features: Create games, manage QR redemptions, and track earnings.',
    // Dashboard
    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.readyToPlay': 'Ready to play games and win amazing prizes?',
    'dashboard.currentBalance': 'Current Balance',
    'dashboard.gameEntriesAvailable': 'game entries available',
    'dashboard.addFunds': 'Add Funds',
    'dashboard.yourPrizeQRCodes': 'Your Prize QR Codes',
    'dashboard.refreshQRCodes': 'Refresh QR Codes',
    'dashboard.gamesRightNow': 'Games Right Now',
    'dashboard.viewAll': 'View All',
    'dashboard.noActiveGames': 'No Active Games',
    'dashboard.checkBackLater': 'Check back later for new restaurant games!',
    'dashboard.tryFreePlay': 'Try Free Play',
    'dashboard.viewAllRestaurantGames': 'View All Restaurant Games',
    'dashboard.howRestaurantGamesWork': 'How Restaurant Games Work',
    'dashboard.joinRestaurantGames': '1. Join Restaurant Games',
    'dashboard.joinRestaurantGamesDesc': 'Browse games created by local restaurants. Any score qualifies - highest score wins the prize!',
    'dashboard.playCompete': '2. Play & Compete',
    'dashboard.playCompeteDesc': 'Each attempt costs the entry fee. Keep playing until the game fills up - highest score wins!',
    'dashboard.winRealPrizes': '3. Win Real Prizes',
    'dashboard.winRealPrizesDesc': 'Winners receive QR codes that can be redeemed at the restaurant for real food and prizes!',
    // Restaurant Dashboard
    'restaurant.dashboard': 'Restaurant Dashboard',
    'restaurant.manageQRTrackEarnings': 'Manage QR redemptions and track your earnings',
    'restaurant.kycRequired': 'KYC Verification Required',
    'restaurant.completeVerificationWithdrawals': 'Complete verification to enable withdrawals',
    'restaurant.loadingDashboard': 'Loading dashboard data...',
    'restaurant.availableBalance': 'Available Balance',
    'restaurant.todayRedemptions': "Today's Redemptions",
    'restaurant.monthlyRevenue': 'Monthly Revenue',
    'restaurant.totalCustomers': 'Total Customers',
    'restaurant.quickActions': 'Quick Actions',
    'restaurant.activeGames': 'Active Games',
    'restaurant.gamesRunning': 'games running',
    'restaurant.pendingQRCodes': 'Pending QR Codes',
    'restaurant.awaitingRedemption': 'Awaiting redemption',
    'restaurant.manageGames': 'Manage Games',
    'restaurant.scanQRCode': 'Scan QR Code',
    'restaurant.withdrawFunds': 'Withdraw Funds',
    'restaurant.completeKYC': 'Complete KYC verification to enable withdrawals',
    'restaurant.recentRedemptions': 'Recent Redemptions',
    'restaurant.noRedemptions': 'No redemptions yet',
    'restaurant.qrCodesAppearHere': 'QR codes will appear here when customers redeem prizes',
    'restaurant.withdrawalHistory': 'Withdrawal History',
    'restaurant.noWithdrawals': 'No withdrawals yet',
    'restaurant.withdrawalHistoryAppear': 'Your withdrawal history will appear here',
    // Games
    'games.restaurantGames': 'Restaurant Games',
    'games.joinGamesWinPrizes': 'Join games created by restaurants and win prizes!',
    'games.insufficientBalance': 'Insufficient Balance',
    'games.needFundsToJoin': 'You need funds to join games.',
    'games.addFundsNow': 'Add funds now',
    'games.noActiveGames': 'No Active Games',
    'games.checkBackLater': 'Check back later for new restaurant games!',
    'games.prizePool': 'Prize Pool',
    'games.entries': 'Entries',
    'games.progress': 'Progress',
    'games.entryFee': 'Entry Fee',
    'games.minScore': 'Min Score',
    'games.singlePlayer': 'Single Player',
    'games.joining': 'Joining...',
    'games.signUpToPlay': 'Sign Up to Play',
    'games.joinGame': 'Join Game',
    'games.howRestaurantGamesWork': 'How Restaurant Games Work',
    'games.joinPlay': '1. Join & Play',
    'games.joinPlayDesc': 'Pay $1 to play a single-player challenge. Score above the minimum to qualify for the prize!',
    'games.competeForVictory': '2. Meet the Challenge',
    'games.competeForVictoryDesc': 'Each game has a minimum score requirement. Reach or exceed it to qualify for the restaurant prize.',
    'games.redeemPrize': '3. Redeem Your Prize',
    'games.redeemPrizeDesc': 'Qualifying players receive a unique QR code that can be redeemed at the restaurant for real food prizes.',
    'language.english': 'English',
    'language.spanish': 'Español'
  },
  es: {
    // Landing page
    'landing.title': 'Dollar App',
    'landing.subtitle': 'Paga $1, juega por premios, canjea en restaurantes.',
    'landing.getStarted': 'COMENZAR',
    'landing.playFreeNow': 'JUGAR GRATIS AHORA',
    'landing.forRestaurants': 'Para Restaurantes',
    'landing.tryOurGames': 'Prueba Nuestros Juegos',
    'landing.howItWorks': 'Cómo Funciona',
    'landing.howItWorksSubtitle': 'Únete a la revolución de juegos gastronómicos con nuestro simple proceso de tres pasos',
    'landing.step1.title': '1. Deposita y Juega',
    'landing.step1.description': 'Agrega fondos al instante. Entra a juegos por solo $1 cada uno.',
    'landing.step2.title': '2. Gana Premios',
    'landing.step2.description': 'Compite por increíbles premios gastronómicos.',
    'landing.step3.title': '3. Canjea y Disfruta',
    'landing.step3.description': 'Usa códigos QR en restaurantes. Verificación instantánea.',
    'landing.cta.title': '¿Listo para Unirte al Juego?',
    'landing.cta.subtitle': 'Comienza a jugar hoy y descubre increíbles experiencias gastronómicas en tu área.',
    'landing.cta.button': 'Crear Cuenta',
    'landing.chooseYourGame': 'Elige Tu Juego',
    'landing.tacoFlyer': 'Volador de Tacos',
    'landing.tacoFlyerDesc': '¡Guía el taco a través de obstáculos!',
    'landing.currentlyPlaying': 'Jugando Actualmente',
    'landing.hamburgerRunner': 'Corredor de Hamburguesas',
    'landing.hamburgerRunnerDesc': '¡Corre y salta a través de obstáculos!',
    'landing.playNow': 'Jugar Ahora',
    'landing.foodBlaster': 'Destructor de Comida',
    'landing.foodBlasterDesc': '¡Dispara a los invasores de comida!',
    'landing.comingSoon': 'Próximamente',
    'landing.pizzaHunter': 'Cazador de Pizza',
    'landing.pizzaHunterDesc': '¡Caza la rebanada perfecta!',
    // Common UI
    'common.loading': 'Cargando...',
    'common.back': 'Atrás',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.close': 'Cerrar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.submit': 'Enviar',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.home': 'Inicio',
    'common.dashboard': 'Panel',
    'common.logout': 'Cerrar Sesión',
    'common.login': 'Iniciar Sesión',
    'common.register': 'Registrarse',
    'common.email': 'Correo',
    'common.password': 'Contraseña',
    'common.username': 'Usuario',
    'common.balance': 'Saldo',
    'common.score': 'Puntuación',
    'common.points': 'Puntos',
    'common.prize': 'Premio',
    'common.winner': 'Ganador',
    'common.players': 'Jugadores',
    'common.games': 'Juegos',
    'common.status': 'Estado',
    'common.active': 'Activo',
    'common.completed': 'Completado',
    'common.pending': 'Pendiente',
    'common.failed': 'Fallido',
    'common.success': 'Éxito',
    'common.error': 'Error',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
    // Auth pages
    'auth.welcomeBack': 'Bienvenido de vuelta',
    'auth.signInToAccount': 'Inicia sesión en tu cuenta de Dollar App',
    'auth.continueWithGoogle': 'Continuar con Google',
    'auth.orContinueWithEmail': 'O continuar con correo',
    'auth.emailAddress': 'Dirección de Correo',
    'auth.enterEmail': 'Ingresa tu correo',
    'auth.enterPassword': 'Ingresa tu contraseña',
    'auth.signIn': 'Iniciar Sesión',
    'auth.dontHaveAccount': '¿No tienes una cuenta?',
    'auth.signUp': 'Regístrate',
    'auth.backToMainSite': '← Volver al sitio principal',
    'auth.createAccount': 'Crear Cuenta',
    'auth.joinCommunity': 'Únete a la comunidad de Dollar App',
    'auth.orCreateWithEmail': 'O crear cuenta con correo',
    'auth.chooseUsername': 'Elige un nombre de usuario',
    'auth.createPassword': 'Crear una contraseña',
    'auth.confirmPassword': 'Confirmar tu contraseña',
    'auth.alreadyHaveAccount': '¿Ya tienes una cuenta?',
    'auth.oauthNote': 'Las cuentas OAuth se crean instantáneamente. Las cuentas de correo requieren verificación.',
    // Restaurant auth
    'restaurant.portal': 'Portal de Restaurante',
    'restaurant.signInToManage': 'Inicia sesión para gestionar tus juegos y canjes de QR',
    'restaurant.viewDemo': 'Ver Demo',
    'restaurant.email': 'Correo del Restaurante',
    'restaurant.enterRestaurantEmail': 'Ingresa el correo de tu restaurante',
    'restaurant.signInToPortal': 'Iniciar Sesión en Portal de Restaurante',
    'restaurant.dontHaveAccount': '¿No tienes una cuenta de restaurante?',
    'restaurant.registerHere': 'Regístrate aquí',
    'restaurant.joinAsRestaurant': 'Únete como Restaurante',
    'restaurant.createGamesAcceptQR': 'Crea juegos y acepta canjes de QR',
    'restaurant.name': 'Nombre del Restaurante',
    'restaurant.enterName': 'Ingresa el nombre de tu restaurante',
    'restaurant.createAccount': 'Crear Cuenta de Restaurante',
    'restaurant.alreadyHaveAccount': '¿Ya tienes una cuenta de restaurante?',
    'restaurant.features': 'Características del Restaurante: Crear juegos, gestionar canjes de QR y rastrear ganancias.',
    // Dashboard
    'dashboard.welcomeBack': 'Bienvenido de vuelta',
    'dashboard.readyToPlay': '¿Listo para jugar y ganar premios increíbles?',
    'dashboard.currentBalance': 'Saldo Actual',
    'dashboard.gameEntriesAvailable': 'entradas de juego disponibles',
    'dashboard.addFunds': 'Agregar Fondos',
    'dashboard.yourPrizeQRCodes': 'Tus Códigos QR de Premio',
    'dashboard.refreshQRCodes': 'Actualizar Códigos QR',
    'dashboard.gamesRightNow': 'Juegos Ahora Mismo',
    'dashboard.viewAll': 'Ver Todos',
    'dashboard.noActiveGames': 'No Hay Juegos Activos',
    'dashboard.checkBackLater': '¡Vuelve más tarde para nuevos juegos de restaurantes!',
    'dashboard.tryFreePlay': 'Prueba Juego Gratis',
    'dashboard.viewAllRestaurantGames': 'Ver Todos los Juegos de Restaurantes',
    'dashboard.howRestaurantGamesWork': 'Cómo Funcionan los Juegos de Restaurantes',
    'dashboard.joinRestaurantGames': '1. Únete a Juegos de Restaurantes',
    'dashboard.joinRestaurantGamesDesc': 'Explora juegos creados por restaurantes locales. ¡Cualquier puntuación califica - la más alta gana el premio!',
    'dashboard.playCompete': '2. Juega y Compite',
    'dashboard.playCompeteDesc': 'Cada intento cuesta la tarifa de entrada. ¡Sigue jugando hasta que el juego se llene - la puntuación más alta gana!',
    'dashboard.winRealPrizes': '3. Gana Premios Reales',
    'dashboard.winRealPrizesDesc': '¡Los ganadores reciben códigos QR que pueden canjearse en el restaurante por comida real y premios!',
    // Restaurant Dashboard
    'restaurant.dashboard': 'Panel de Restaurante',
    'restaurant.manageQRTrackEarnings': 'Gestiona canjes de QR y rastrea tus ganancias',
    'restaurant.kycRequired': 'Verificación KYC Requerida',
    'restaurant.completeVerificationWithdrawals': 'Completa la verificación para habilitar retiros',
    'restaurant.loadingDashboard': 'Cargando datos del panel...',
    'restaurant.availableBalance': 'Saldo Disponible',
    'restaurant.todayRedemptions': 'Canjes de Hoy',
    'restaurant.monthlyRevenue': 'Ingresos Mensuales',
    'restaurant.totalCustomers': 'Total de Clientes',
    'restaurant.quickActions': 'Acciones Rápidas',
    'restaurant.activeGames': 'Juegos Activos',
    'restaurant.gamesRunning': 'juegos ejecutándose',
    'restaurant.pendingQRCodes': 'Códigos QR Pendientes',
    'restaurant.awaitingRedemption': 'Esperando canje',
    'restaurant.manageGames': 'Gestionar Juegos',
    'restaurant.scanQRCode': 'Escanear Código QR',
    'restaurant.withdrawFunds': 'Retirar Fondos',
    'restaurant.completeKYC': 'Completa la verificación KYC para habilitar retiros',
    'restaurant.recentRedemptions': 'Canjes Recientes',
    'restaurant.noRedemptions': 'No hay canjes aún',
    'restaurant.qrCodesAppearHere': 'Los códigos QR aparecerán aquí cuando los clientes canjeen premios',
    'restaurant.withdrawalHistory': 'Historial de Retiros',
    'restaurant.noWithdrawals': 'No hay retiros aún',
    'restaurant.withdrawalHistoryAppear': 'Tu historial de retiros aparecerá aquí',
    // Games
    'games.restaurantGames': 'Juegos de Restaurantes',
    'games.joinGamesWinPrizes': '¡Únete a juegos creados por restaurantes y gana premios!',
    'games.insufficientBalance': 'Saldo Insuficiente',
    'games.needFundsToJoin': 'Necesitas fondos para unirte a juegos.',
    'games.addFundsNow': 'Agregar fondos ahora',
    'games.noActiveGames': 'No Hay Juegos Activos',
    'games.checkBackLater': '¡Vuelve más tarde para nuevos juegos de restaurantes!',
    'games.prizePool': 'Pozo de Premios',
    'games.entries': 'Entradas',
    'games.progress': 'Progreso',
    'games.entryFee': 'Tarifa de Entrada',
    'games.minScore': 'Puntuación Mín',
    'games.singlePlayer': 'Un Jugador',
    'games.joining': 'Uniéndose...',
    'games.signUpToPlay': 'Regístrate para Jugar',
    'games.joinGame': 'Unirse al Juego',
    'games.howRestaurantGamesWork': 'Cómo Funcionan los Juegos de Restaurantes',
    'games.joinPlay': '1. Únete y Juega',
    'games.joinPlayDesc': '¡Paga $1 para jugar un desafío de un solo jugador. Supera la puntuación mínima para calificar para el premio!',
    'games.competeForVictory': '2. Supera el Desafío',
    'games.competeForVictoryDesc': 'Cada juego tiene un requisito de puntuación mínima. Alcánzala o supérala para calificar para el premio del restaurante.',
    'games.redeemPrize': '3. Canjea tu Premio',
    'games.redeemPrizeDesc': 'Los jugadores que califican reciben un código QR único que puede canjearse en el restaurante por premios de comida reales.',
    'language.english': 'English',
    'language.spanish': 'Español'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};